# Generated by Django 3.2 on 2021-04-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('distancia', models.IntegerField(default=0)),
                ('sexo', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=255)),
            ],
        ),
    ]
