# Generated by Django 3.2 on 2021-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210415_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esportes',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
